### ISSUE TITLE
Cleaning experiment variables for multiple choice

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/stopadforms#35]
There is a problem with how the experiment variables are cleaned in `clean_experiment_variables()`, but only if there are multiple choice, such as in the case of routes of administration. Users can choose multiple ways that the drug was administered. An example of the problem is quoted from PR #32.

>If one experiment, let's say ld50, has multiple routes of administration for the drug, then the JSON variables will be ld50.experiments.route1, ld50.experiments.route2, ld50.experiments.route3, etc. The way the code is written now, this turns into 3 ld50 experiments (ld50 [1], ld50 [2], ld50 [3]), where all the variables except route2 and route3 will be under ld50 [1]. ld50 [2] will have a single row for route2 and ld50 [3] will have a single row for route3.

At the moment, I'm not sure how best to tell which route(s) got to which experiment, if there is more than one experiment and at least one has multiple routes.

Example:
Experiment [1] has 2 routes and experiment [2] has 1 route. The JSON variables should be something like:
- experiment.name1
- experiment.route1
- experiment.route2
- experiment.name2
- experiment.route2

The ordering is potentially the only way to tell which route2 goes with which experiment, but I'm not completely sure we can rely on order.

**Comment by karawoo** [comment]
I think that the most robust way to handle this will be to use the structure of the json data, rather than flattening the nested structure and then trying to recreate it based on regex parsing of the names. Unfortunately, we have _some_ tricky data wrangling to do no matter what, because the form data is structured such that sometimes the data we're interested in displaying (the responses users entered into the form) are at different levels of nestedness.

I played around with this today and came up with an approach that seems in the right direction, though I don't remember the exact structure of the data that we're currently using for display in the app, so it might need some tweaks. My code does the following:

1. Downloads one JSON file for testing
2. Reads it in as a nested list
3. Creates a function that, for each element in the list:
  a. if it contains `"experiments"`, goes through each experiment and creates a data frame of the section name (with number corresponding to the experiment), variables, and response values. 
  b. if it does not have experiments, just creates a data frame of the section name (no number added), variables, and response values.
  c. if the section is empty, returns `NULL`
4. Applies the function above to each element in the list and returns a data frame, in which the response column can be a list-column, or can be unnested.

Can we chat about this later in the week? I may have oversimplified things in my test example, and I'm not sure how this would fit in with the rest of what the app does. But hopefully some piece of it may be useful.

``` r
library("reticulate")
synapse <- import("synapseclient")
syn <- synapse$Synapse()
syn$login()
library("synapseforms")
library("jsonlite")
library("tidyverse")

# Get data to test with
url <- synapseforms:::get_ps_url(
  syn = syn,
  file_handle_id = 48185890, # my test submission from today
  form_data_id = 209
)
synapseforms:::download_form_file(url, "test.json", "~/Desktop/")
dat <- fromJSON("test.json", simplifyDataFrame = FALSE)

create_table_from_section <- function(data, section, unnest = FALSE) {
  ## Create a tibble with section name, variables, and response values
  create_table_from_values <- function(data, section, unnest) {
    if (isTRUE(unnest)) {
      tibble::tibble(
        section = section,
        variable = names(unlist(data)),
        values = as.character(unlist(data))
      )
    } else {
      tibble::tibble(
        section = section,
        variable = names(data),
        values = data
      )
    }
  }

  ## If no data, return NULL
  if (length(data) == 0) {
    return(NULL)
  } else if (length(names(data)) == 1 && names(data) == "experiments") {
    ## If "experiments" is the only element, we need to go deeper to extract the
    ## info for each experiment separately. The section name needs to have a
    ## number appended so we can differentiate
    dat <- purrr::imap_dfr(
      data[["experiments"]],
      function(data, index) {
        create_table_from_values(
          data = data,
          section = as.character(glue::glue("{section} {index}")),
          unnest = unnest
        )
      }
    )
  } else {
    ## If the section does not contain separate experiments, then we return the
    ## data from the section
    dat <- create_table_from_values(data = data, section = section, unnest = unnest)
  }
  dat
}

## Create data frame, one version with list column of values (not sure how these
## would be displayed), another version with unnested values
full_table_listcol <- imap_dfr(dat, create_table_from_section)
full_table_unnest <- imap_dfr(dat, create_table_from_section, unnest = TRUE)

## See a few rows as an example:
filter(full_table_listcol, section == "basic")
#> # A tibble: 7 x 3
#>   section variable                           values   
#>   <chr>   <chr>                              <list>   
#> 1 basic   molecular_target                   <chr [1]>
#> 2 basic   moa_description                    <chr [1]>
#> 3 basic   therapeutic_approach               <chr [1]>
#> 4 basic   therapeutic_indication_description <chr [1]>
#> 5 basic   water_soluble                      <chr [1]>
#> 6 basic   route                              <chr [5]>
#> 7 basic   orally_active                      <chr [1]>
filter(full_table_unnest, section == "basic")
#> # A tibble: 11 x 3
#>    section variable                           values            
#>    <chr>   <chr>                              <chr>             
#>  1 basic   molecular_target                   lsdkfj            
#>  2 basic   moa_description                    sdlfjsdlkfj       
#>  3 basic   therapeutic_approach               symptomatic       
#>  4 basic   therapeutic_indication_description aldskfalskdf      
#>  5 basic   water_soluble                      no                
#>  6 basic   route1                             oral              
#>  7 basic   route2                             sublingual        
#>  8 basic   route3                             injection         
#>  9 basic   route4                             transdermal       
#> 10 basic   route5                             formulated_in_food
#> 11 basic   orally_active                      yes
```
